os:
  - linux

language: php

php:
  - '7.3'

services:
  - mysql

addons:
  sonarcloud:
    organization: "schmidtflo"
    token:
      secure: "JljRFYigUO2xCgPmiaVjLY/HtEUP26OlnRNbIfNSpaGe9aznaaJdgpVlQnP+k2zRlb8VHmJr1ERiO4HwKz+UFgd4KKR7R5q+AnFGSnufX/CCkbWuQC9cLQRb3HdRDG8cMy3k6g+dVZgqxval9UCx1A0OnQY0j/iY5gxSSNZPuPVtvSqXPDgPxygwqyqDGtZkhsioEgb5JBI4Z+TKLmY8+CsTA7fCq1HGHJu0mIx38V/X3DZ98pmnBG9zVtYCtFFjzorBTUlGFY9N7TFsq0eoKDY2owXzH/aBARO7YfvRAyY3DGzbx3J8u18r3vm53NQGahsIPCRxbVAfxjHX6jaqbZDwYilXHjYrgG/RdxYJxosxfbf0cEGGOsPQmNz3wIPM/FPCUsegUyOkJTeFu0MEpqpVwZtDkBXmaa/XJfU58DNqRBhbq4ODq8zgy4dS55vbLK4/f2Y4BcksQ3COTJth4tAbx72zXUftEdqWjYQPqFuFVwW6OCDYMrgRsLQkILru1mFMn5tXAxgk/RAHSjwc8WPVQRjyvPA8a8JctctWbSAwHVxz40sHCmwbELAxTxylIzLIvK4y3/cOoh3RSb5kKaJwFUsddKxemKxjSpOWO3WheTwznbS+9mXbJvX5hbXyQabnxqyZvC7t7grQcZuca0rEdPFUYgT6o3WqUZnsjlI="


cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - mysql -e 'create database travis_test;'
  - composer self-update
  - composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  #	- npm install npm@latest -g
  #	- npm install -g jshint
  # - npm install

jobs:
  include:
    - stage: test
      script:
        - vendor/bin/phpunit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
        - sonar-scanner
        - codecov

#	- phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
#	- npm run production
#	- jshint resources/assets/js/modules/*
